{% set version = "0.4.0" %}

package:
  name: tox-venv
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tox-venv/tox-venv-{{ version }}.tar.gz
  sha256: ea29dc7b21a03951e1e2bd7f3474bbf315657c5454224a5674b2896e9bbb795c

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - tox >=3.8.1

test:
  requires:
    - pip
    - pytest
    - pytest-mock
    - python {{ python_min }}
  source_files:
    - tests
  imports:
    - tox_venv
  commands:
    - pip check
    - pytest -vv --tb=long --color=yes -k "not matchingdependencies_latest and not result_json"

about:
  home: https://github.com/tox-dev/tox-venv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Use Python 3 venvs for Python 3 test environments '

extra:
  recipe-maintainers:
    - bollwyvl
